name: server
description: Hosts a web server that receives note requests and relays them to other plugins.
authors: [ TehBrian ]
website: https://github.com/mcmidi-uwu/server

version: ${version}
main: xyz.tehbrian.mcmidi.serverpaper.ServerPlugin
api-version: 1.18
